{% set name = "pybads" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 36d4cd4d8b3da2c6fdb774d53ae176ccfd407542685cc8900a5a4e3facfd49a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - gpyreg >=1.4.0
    - matplotlib-base >=3.9.0
    - numpy >=2.0.0
    - scipy >=1.13.0

test:
  imports:
    - pybads
  commands:
    - pip check
    - python -m pytest --pyargs pybads -x -vv
  requires:
    - pip
    - python {{ python_min }}
    - pytest >=6.2.5
    - pytest-mock >=3.6.1

about:
  home: https://acerbilab.github.io/pybads/
  summary: Bayesian Adaptive Direct Search in Python.
  description: |
    PyBADS is a Python implementation of the Bayesian Adaptive Direct Search (BADS) algorithm for solving difficult and moderately expensive optimization problems.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://acerbilab.github.io/pybads/
  dev_url: https://github.com/acerbilab/pybads/

extra:
  recipe-maintainers:
    - GurjeetSinghSangra
    - lacerbi
