{% set name = "pybads" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 967892b32eb239c3ceba10365bdcde6e13b63d530c5f439d6e26c2ccb2872672

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - cma >=3.1.0
    - corner >=2.2.1
    - dill >=0.3.5.1
    - gpyreg >=0.1.0
    - imageio >=2.13.5
    - matplotlib-base >=3.5.1
    - numpy >=1.22.1
    - plotly >=5.11.0
    - pytest >=6.2.5
    - pytest-mock >=3.6.1
    - pytest-rerunfailures >=10.2
    - scipy >=1.7.3

test:
  imports:
    - pybads
  commands:
    - pip check
    - python -m pytest  --pyargs pybads --reruns=5 -x -vv
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://acerbilab.github.io/pybads/
  summary: Bayesian Adaptive Direct Search in Python.
  description: |
    PyBADS is a Python implementation of the Bayesian Adaptive Direct Search (BADS) algorithm for solving difficult and moderately expensive optimization problems.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://acerbilab.github.io/pybads/
  dev_url: https://github.com/acerbilab/pybads/

extra:
  recipe-maintainers:
    - GurjeetSinghSangra
    - lacerbi
