{% set name = "pybads" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: df76b900aae79694432d37e8f78bcc5a9acdeaade3459db183edda13be5cdc97

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - gpyreg >=1.3.3
    - matplotlib-base >=3.5.1
    - numpy >=1.22.1
    - scipy >=1.7.3

test:
  imports:
    - pybads
  commands:
    - pip check
    - python -m pytest --pyargs pybads --reruns=5 -x -vv
  requires:
    - pip
    - python {{ python_min }}
    - pytest >=6.2.5
    - pytest-mock >=3.6.1
    - pytest-rerunfailures >=10.2

about:
  home: https://acerbilab.github.io/pybads/
  summary: Bayesian Adaptive Direct Search in Python.
  description: |
    PyBADS is a Python implementation of the Bayesian Adaptive Direct Search (BADS) algorithm for solving difficult and moderately expensive optimization problems.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://acerbilab.github.io/pybads/
  dev_url: https://github.com/acerbilab/pybads/

extra:
  recipe-maintainers:
    - GurjeetSinghSangra
    - lacerbi
